### PR TITLE
strlen version

### PR DESCRIPTION
**Pull request by marlier**
This is very important.

### CODE REVIEW

**Comment by agaman** [comment]
I'm against this. Any string that has 42 characters "is 42" ?

What about this string?

```
This string is _NOT_ the number forty two.
```

**Comment by marlier** [comment]
It == 42. Duh.

**Comment by hamiltonkibbe** [comment]
We need to handle this corner case:

`is42("fourteenthousandeighthundredandeightythree").should.equal(false)`

**Comment by marlier** [comment]
With spaces it's 48.  So no issue.

**Pull request closed without merging**
